### ISSUE TITLE
Add `operationId` support

### ISSUE THREAD

**Issue by romalytvynenko** [dedoc/scramble#129]
By default, use `@operationId` php doc tag value. If it is not set, use route name, if it is not set, use `{base controller name}.{method name}` convention.

If using route name, maybe consider removing name prefix if some is set on API level.

So for an action `\App\Http\Controllers\EventsController@store` the operation id would be `events.store` if route has no name and `@operationId` tag.

**Comment by HelgeSverre** [comment]
For anyone that desperately need this functionality right now;
Like me, since ChatGPT Plugins require the operationId field to work. 

*You're in luck!*
The developers made it easy to extend this package with Extensions. (Good work!)


Here is what you do.


## 1. Create a new [Extension](https://scramble.dedoc.co/developers/extensions) (i put mine in ```app/Extensions```)
```php
<?php

namespace App\Extensions;

use Dedoc\Scramble\Extensions\OperationExtension;
use Dedoc\Scramble\Support\Generator\Operation;
use Dedoc\Scramble\Support\RouteInfo;
use Illuminate\Support\Arr;

class AddOperationIdExtensionSupport extends OperationExtension
{
    public function handle(Operation $operation, RouteInfo $routeInfo)
    {
        if ($operationId = $routeInfo->phpDoc()->getTagsByName("@operationId")) {
            if ($value = trim(Arr::first($operationId)?->value?->value)) {
                $operation->setOperationId($value);
            }
        }
    }
}
```

## 2. Register your extension in the ```config/scramble.php``` config file:

*Note:* If you don't have this file in your config folder, you need to [publish it](https://scramble.dedoc.co/installation#publishing-config) by running this command
```shell
php artisan vendor:publish --provider="Dedoc\Scramble\ScrambleServiceProvider" --tag="scramble-config"

```

Now register the extension in the "extensions" array.

```php
<?php

use App\Extensions\AddOperationIdExtensionSupport;

return [
    // ...
    
    'extensions' => [
        AddOperationIdExtensionSupport::class,
    ],
];

``` 

## 3. Annotate your method with ```@operationId```

Example:
```php
<?php

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\SearchProducts;
use App\Http\Resources\Api\ProductResource;
use App\Models\Product;

class ProductController extends Controller
{
    /**
     * Search for products
     *
     * Useful for searching for groceries and various product to find the price, ingredients and nutritional information
     *
     * @operationId searchProducts
     */
    public function index(SearchProducts $request)
    {
        return ProductResource::collection(
            Product::query()->paginate()
        );
    }
}
```


## 4. Done!

Your OpenAPI spec should now include the operationId.

![image](https://github.com/dedoc/scramble/assets/1089652/d609b461-e6ec-49d7-a6b9-d9ffd280ea27)
