### ISSUE TITLE
Problem with returning array of strings in documentation

### ISSUE THREAD

**Issue by slnw** [dedoc/scramble#158]
![Screenshot 2023-07-17 at 18 07 47](https://github.com/dedoc/scramble/assets/26124406/68823424-bda9-460c-8791-5a34cbd3e233)

I think there is no way to describe the current response within the current structure.

trying to use - https://scramble.dedoc.co/usage/response#arbitrary-responses to respond with this info.

**Comment by romalytvynenko** [comment]
Hey. Can you please leave more details? Code examples will be good

**Comment by slnw** [comment]
![Screenshot 2023-07-18 at 08 46 46](https://github.com/dedoc/scramble/assets/26124406/6cc272d6-531b-40fc-b624-e14337384056)

Hi @romalytvynenko, this is the controller for the service. the TagsService returns array of tags ['tag1', 'tag2'..]

**Comment by romalytvynenko** [comment]
@slnw I see!

The issue here is that `array[]` is not correct type annotation. It should be `string[]`.

Also I recommend using `@response` annotation if you want to document the response yourself.

<img width="365" alt="image" src="https://github.com/dedoc/scramble/assets/6153876/8dab5b39-0171-4004-9b91-853680b2164d">

<img width="784" alt="image" src="https://github.com/dedoc/scramble/assets/6153876/3d7d8c3c-4fab-458c-8aa6-95c3b07c8532">

Closing the issue, feel free to re-open if you have any other question.
