### ISSUE TITLE
JsonResource toArray method type hint

### ISSUE THREAD

**Issue by m-lotze** [dedoc/scramble#34]
Hi there,

Thank you for this great package!

Probably not a bug, since the laravel `JsonResource` class `toArray` method does not use a type hint. But it seems like the JsonResource is only resolving the model fields, when the `toArray` method has no type hint.

This works:

```
class TodoItemResource extends JsonResource
{
    public function toArray()
    {
        return [
            'id' => $this->id,
        ];
    }
}
```

This shows `body` of `TodoItemResource` as `string`:

```
class TodoItemResource extends JsonResource
{
    public function toArray(): array
    {
        return [
            'id' => $this->id,
        ];
    }
}
```

Just wondering why this makes a difference?

**Comment by romalytvynenko** [comment]
Hey @m-lotze 

Thanks for reaching out. 

When Scramble analyzes types and encounters type hints, it doesn't analyze the method's body itself. Hence lost information about what method actually returns.

I'm considering changing this behavior because this is definitely not what I'd expect in case you've demonstrated. 

Thanks.
